import { FeedbackItem, MetricCardData } from "@/types/feedback";

// Workspace user mock
export const mockUser = {
    name: "John Doe",
    email: "demo.john@loop.ai",
    avatarInitials: "JD",
    role: "Workspace Admin",
};

// Day 2 Dashboard Cards
export const mockMetrics: MetricCardData[] = [
    {
        title: "Total Feedback",
        value: "1,482",
        change: "+12.5%",
        isPositive: true,
        timeframe: "vs last month",
        iconName: "MessageSquare",
    },
    {
        title: "Positive Feedback",
        value: "71.2%",
        change: "+4.1%",
        isPositive: true,
        timeframe: "vs last month",
        iconName: "Smile",
    },
    {
        title: "Negative Feedback",
        value: "18.3%",
        change: "-3.5%",
        isPositive: true, // positive because negative sentiment went down
        timeframe: "vs last month",
        iconName: "Frown",
    },
    {
        title: "Neutral Feedback",
        value: "10.5%",
        change: "-0.6%",
        isPositive: true,
        timeframe: "vs last month",
        iconName: "Meh",
    },
    {
        title: "Active Users",
        value: "3,842",
        change: "+8.7%",
        isPositive: true,
        timeframe: "vs last week",
        iconName: "Users",
    },
    {
        title: "AI Insights",
        value: "94.2%",
        change: "+0.8%",
        isPositive: true,
        timeframe: "from relative base",
        iconName: "Sparkles",
    }
];

// Feedback items list supporting: Customer Name, Feedback, Sentiment, Rating, Date, Status
export const mockFeedbackList: FeedbackItem[] = [
    {
        id: "fb-1",
        source: "email",
        customerName: "Alice Vance",
        customerEmail: "alice@vancetech.io",
        sentiment: "negative",
        category: "bug",
        content: "The billing section throws an unexpected 500 error when attempting to download our monthly PDF invoices. This is blocking our accounting team from closing their accounts.",
        status: "new",
        createdAt: "2026-08-05T18:45:00Z",
        confidenceScore: 0.98,
        rating: 2,
        aiSummary: "Billing invoice PDF download failures causing accounting blocker.",
        suggestedAction: "Check Sentry for PDF generation library errors and deploy hotfix.",
        keywords: ["billing", "pdf", "500-error", "accounting"]
    },
    {
        id: "fb-2",
        source: "playstore",
        customerName: "David Kim",
        customerEmail: "david.kim@gmail.com",
        sentiment: "positive",
        category: "ui_ux",
        content: "Absolutely love the new dark mode design! Navigator gestures are so smooth and simple. Great job on the 1.4 update.",
        status: "resolved",
        createdAt: "2026-08-05T12:30:00Z",
        confidenceScore: 0.95,
        rating: 5,
        aiSummary: "Highly positive feedback regarding Version 1.4 dark mode UI.",
        suggestedAction: "Forward user appreciation to the design team.",
        keywords: ["dark-mode", "ui", "gestures", "mobile"]
    },
    {
        id: "fb-3",
        source: "chat",
        customerName: "Sophie Dupont",
        customerEmail: "sophie@dupontconsulting.fr",
        sentiment: "neutral",
        category: "feature_request",
        content: "Would it be possible to add webhook notifications for MS Teams? We have migrated away from Slack and want realtime alerts on our support channel for VIP tags.",
        status: "in_progress",
        createdAt: "2026-08-04T15:10:00Z",
        confidenceScore: 0.89,
        rating: 4,
        aiSummary: "Integration request for MS Teams webhook notifications.",
        suggestedAction: "Add to API integrations backlog and prioritize based on enterprise requests.",
        keywords: ["ms-teams", "webhooks", "integrations", "notifications"]
    },
    {
        id: "fb-4",
        source: "twitter",
        customerName: "Alex Mercer",
        customerEmail: "alex@mercer.dev",
        sentiment: "negative",
        category: "performance",
        content: "Initial script loading times for the embedded page widget are taking way too long on mobile devices (almost 4.2 seconds). Pls optimize chunk size and leverage edge CDN caching.",
        status: "new",
        createdAt: "2026-08-04T09:20:00Z",
        confidenceScore: 0.97,
        rating: 1,
        aiSummary: "Slow loading times (4.2s) of the embedded widget on mobile devices.",
        suggestedAction: "Audit page widget package size, apply treeshaking, and configure Cloudflare cache layers.",
        keywords: ["performance", "widget", "mobile", "cdn", "loading-speed"]
    },
    {
        id: "fb-5",
        source: "appstore",
        customerName: "Elena Rostova",
        customerEmail: "elena.r@ya.ru",
        sentiment: "neutral",
        category: "pricing",
        content: "The custom enterprise plans require calling sales, but a clear overview for start-up bundles would save developer teams a lot of initial negotiation and back-and-forth.",
        status: "in_progress",
        createdAt: "2026-08-03T20:15:00Z",
        confidenceScore: 0.88,
        rating: 3,
        aiSummary: "Desire for transparent self-serve startup/developer plans.",
        suggestedAction: "Propose tier-based developer packaging to product marketing.",
        keywords: ["pricing", "startup", "self-serve", "enterprise"]
    },
    {
        id: "fb-6",
        source: "email",
        customerName: "Marcus Sterling",
        customerEmail: "marcus@sterling.co.uk",
        sentiment: "positive",
        category: "performance",
        content: "Query response time has dropped under 50ms in Western Europe regions. The migration to Edge databases has been a remarkable improvement.",
        status: "resolved",
        createdAt: "2026-08-03T14:22:00Z",
        confidenceScore: 0.99,
        rating: 5,
        aiSummary: "Western Europe DB latency decreased below 50ms post edge migration.",
        suggestedAction: "Collect metrics for promotional dev blog post.",
        keywords: ["performance", "latency", "edge-db", "europe"]
    },
    {
        id: "fb-7",
        source: "survey",
        customerName: "Nisha Patel",
        customerEmail: "nisha.patel@techsolutions.in",
        sentiment: "negative",
        category: "ui_ux",
        content: "The dashboard is hard to navigate on mobile devices. The text boxes overflow the margins and the side bars block the main table columns.",
        status: "new",
        createdAt: "2026-08-02T11:05:00Z",
        confidenceScore: 0.91,
        rating: 2,
        aiSummary: "Mobile responsiveness issue causing components to overflow viewport.",
        suggestedAction: "Verify responsive CSS breakdown; fix table overflow scroll rules.",
        keywords: ["mobile", "ui-overflow", "responsive", "dashboard"]
    },
    {
        id: "fb-8",
        source: "google",
        customerName: "Thomas Muller",
        customerEmail: "t.muller@munichparts.de",
        sentiment: "positive",
        category: "other",
        content: "Customer support was extremely helpful when we had issues setting up SAML single sign-on. They jumped on a Zoom invite and resolved it in 10 minutes.",
        status: "resolved",
        createdAt: "2026-08-02T09:12:00Z",
        confidenceScore: 0.96,
        rating: 5,
        aiSummary: "Praise for customer support assisting with SAML SSO setup.",
        suggestedAction: "Recognize the support engineer who handled this ticket.",
        keywords: ["sso", "saml", "support", "setup"]
    },
    {
        id: "fb-9",
        source: "website",
        customerName: "Rachel Green",
        customerEmail: "rgreen@fashionloft.com",
        sentiment: "neutral",
        category: "feature_request",
        content: "Is there a way to export analytics charts into PDF format for our quarterly presentations? Right now we have to manually screenshot them.",
        status: "new",
        createdAt: "2026-08-01T16:30:00Z",
        confidenceScore: 0.92,
        rating: 3,
        aiSummary: "Request for PDF export function on analytics dashboard.",
        suggestedAction: "Consider implementing dashboard print layout style sheets or PDF export button.",
        keywords: ["charts", "export", "pdf", "analytics"]
    },
    {
        id: "fb-10",
        source: "email",
        customerName: "Gregory House",
        customerEmail: "house.md@diagnostics.org",
        sentiment: "negative",
        category: "bug",
        content: "The auto-refresh logs panel is flashing red intermittently. This happens when there is a websocket reconnection. It is extremely annoying and triggers migraine issues.",
        status: "new",
        createdAt: "2026-08-01T14:05:00Z",
        confidenceScore: 0.95,
        rating: 1,
        aiSummary: "Websocket reconnection loop causing UI to flash red intermittently.",
        suggestedAction: "Gracefully display reconnection state with quiet spinner instead of flashing banners.",
        keywords: ["websocket", "ui-flashing", "monitoring", "bug"]
    },
    {
        id: "fb-11",
        source: "appstore",
        customerName: "Yuki Tanaka",
        customerEmail: "yuki.t@cybermedia.jp",
        sentiment: "positive",
        category: "performance",
        content: "Very satisfied with the data sync speed. We updated our catalog and it was modified across 100 client apps within seconds. Keep it up!",
        status: "resolved",
        createdAt: "2026-07-31T08:50:00Z",
        confidenceScore: 0.97,
        rating: 5,
        aiSummary: "User is extremely satisfied with catalog sync performance speed.",
        suggestedAction: "No action. Mark as success story.",
        keywords: ["sync", "latency", "realtime", "catalog"]
    },
    {
        id: "fb-12",
        source: "twitter",
        customerName: "Brenda Larson",
        customerEmail: "blarson@marketingpro.net",
        sentiment: "neutral",
        category: "pricing",
        content: "Enjoying the free trial, but the jump from free to developer tier is rather steep ($0 to $49/mo). Can there be a cheaper starter hobby tier for side projects?",
        status: "new",
        createdAt: "2026-07-30T17:40:00Z",
        confidenceScore: 0.86,
        rating: 3,
        aiSummary: "Request for low-cost hobby pricing tier between free and $49 level.",
        suggestedAction: "Relay pricing feedback to finance during model review.",
        keywords: ["pricing-tiers", "hobby-plan", "conversion"]
    },
    {
        id: "fb-13",
        source: "website",
        customerName: "Carlos Santana",
        customerEmail: "carlos@gitgrooves.dev",
        sentiment: "negative",
        category: "performance",
        content: "API rate limiting responds with a blank page rather than a JSON formatted payload. It makes debugging automated scripts difficult when we hit limits.",
        status: "in_progress",
        createdAt: "2026-07-30T10:15:00Z",
        confidenceScore: 0.93,
        rating: 2,
        aiSummary: "Rate limiter returning HTML instead of structured JSON response.",
        suggestedAction: "Update API middleware middleware/rate-limit to return structured JSON error code 429.",
        keywords: ["api", "rate-limit", "json", "debugging"]
    },
    {
        id: "fb-14",
        source: "google",
        customerName: "Emma Watson",
        customerEmail: "emma.watson@uni-education.edu",
        sentiment: "positive",
        category: "ui_ux",
        content: "The clean layouts and accessibility options are wonderful. Keyboard shortcut mappings make handling repetitive reviews so much faster.",
        status: "resolved",
        createdAt: "2026-07-29T11:22:00Z",
        confidenceScore: 0.94,
        rating: 5,
        aiSummary: "Praise for keyboard shortcuts and design accessibility features.",
        suggestedAction: "Document client shortcut mappings to improve user guides.",
        keywords: ["shortcuts", "accessibility", "accessibility", "ux"]
    },
    {
        id: "fb-15",
        source: "email",
        customerName: "Daniel Craig",
        customerEmail: "agent007@mi6.gov.uk",
        sentiment: "negative",
        category: "other",
        content: "Security audit flagged weak SSH cipher support on the storage bucket sync endpoints. We need this resolved immediately to maintain compliance.",
        status: "new",
        createdAt: "2026-07-29T08:00:00Z",
        confidenceScore: 0.98,
        rating: 1,
        aiSummary: "Security audit reported outdated SSH ciphers on sync endpoint.",
        suggestedAction: "Apply updated cipher list in Terraform SSH profile config.",
        keywords: ["security", "ssh", "compliance", "encryption"]
    },
    {
        id: "fb-16",
        source: "playstore",
        customerName: "Oliver Kahn",
        customerEmail: "okahn@titansecurity.de",
        sentiment: "neutral",
        category: "bug",
        content: "Push notifications show the raw template variables sometimes (e.g. {{customerName}} has sent feedback) instead of actual compiled values. Please review template engine.",
        status: "in_progress",
        createdAt: "2026-07-28T16:10:00Z",
        confidenceScore: 0.94,
        rating: 3,
        aiSummary: "Push template replacement fails under high-concurrency loops.",
        suggestedAction: "Check localization engine parser triggers in mobile push emitter.",
        keywords: ["notifications", "push", "templating-engine", "localization"]
    },
    {
        id: "fb-17",
        source: "chat",
        customerName: "Lily Evans",
        customerEmail: "levans@hogwarts.org",
        sentiment: "positive",
        category: "feature_request",
        content: "It would be amazing if the AI could tag issues based on custom keywords we enter. Like 'Harry' or 'Magic' so we can bucket tickets into specialized folders.",
        status: "new",
        createdAt: "2026-07-28T14:05:00Z",
        confidenceScore: 0.91,
        rating: 4,
        aiSummary: "Request to support user-defined custom keywords for auto-tagging.",
        suggestedAction: "Draft UI schema for adding custom keywords into customer settings panel.",
        keywords: ["ai-tagging", "custom-keywords", "folders"]
    },
    {
        id: "fb-18",
        source: "email",
        customerName: "Bruce Wayne",
        customerEmail: "bruce@waynecorp.com",
        sentiment: "positive",
        category: "performance",
        content: "The offline syncing works perfectly, even in remote areas (like tunnels or subways) it caches feedback queues and pushes them when connection restores.",
        status: "resolved",
        createdAt: "2026-07-27T19:30:00Z",
        confidenceScore: 0.96,
        rating: 5,
        aiSummary: "Offline mode works reliably on subways, syncing back properly.",
        suggestedAction: "Add to client testimonials list.",
        keywords: ["offline-mode", "sync", "mobile", "cache"]
    },
    {
        id: "fb-19",
        source: "twitter",
        customerName: "Amanda Waller",
        customerEmail: "awaller@cadmus.gov",
        sentiment: "negative",
        category: "pricing",
        content: "Charging per admin user instead of total feedback volume seems punitive. We have 50 agents who only log in once a month but need full seats.",
        status: "new",
        createdAt: "2026-07-27T10:12:00Z",
        confidenceScore: 0.89,
        rating: 2,
        aiSummary: "Seat-based pricing model criticized by multi-agent organizations.",
        suggestedAction: "Review read-only agent roles or usage tier structure.",
        keywords: ["pricing", "billing-seats", "agents"]
    },
    {
        id: "fb-20",
        source: "google",
        customerName: "Peter Parker",
        customerEmail: "peter@dailybugle.com",
        sentiment: "negative",
        category: "ui_ux",
        content: "The image upload tool has no crop or resizing utility. Every screenshot I upload gets stretched out of proportion in the details viewer.",
        status: "in_progress",
        createdAt: "2026-07-26T15:40:00Z",
        confidenceScore: 0.92,
        rating: 2,
        aiSummary: "Stretched screenshot images in drawer due to lack of CSS aspect containment.",
        suggestedAction: "Apply object-fit: contain to feedback screenshot modals.",
        keywords: ["uploads", "screenshot", "ui", "aspect-ratio"]
    },
    {
        id: "fb-21",
        source: "survey",
        customerName: "Tony Stark",
        customerEmail: "tony@starkindustries.com",
        sentiment: "positive",
        category: "ui_ux",
        content: "The API Explorer interface is sleek. Sandbox testing without copying API keys back and forth was an excellent design choice.",
        status: "resolved",
        createdAt: "2026-07-26T12:00:00Z",
        confidenceScore: 0.98,
        rating: 5,
        aiSummary: "Feedback praises the design of the inline API sandbox explorer.",
        suggestedAction: "Highlight sandbox UX features during product feature release.",
        keywords: ["sandbox", "api-explorer", "developer-ux", "documentation"]
    },
    {
        id: "fb-22",
        source: "email",
        customerName: "Lara Croft",
        customerEmail: "lara@tombadventures.com",
        sentiment: "neutral",
        category: "other",
        content: "The system is exporting CSV files using carriage returns that split notes on MS Excel imports. Please check file formatting encoding.",
        status: "resolved",
        createdAt: "2026-07-25T11:15:00Z",
        confidenceScore: 0.90,
        rating: 3,
        aiSummary: "CSV export breaks lines on MS Excel due to CRLF carriage return formatting.",
        suggestedAction: "Set RFC 4180 strict double-quoting standards on export utility.",
        keywords: ["csv", "excel", "export", "encoding"]
    },
    {
        id: "fb-23",
        source: "playstore",
        customerName: "Clark Kent",
        customerEmail: "ckent@dailyplanet.com",
        sentiment: "negative",
        category: "bug",
        content: "The search bar glitches out whenever I type letters containing accents (like é or ü). It empties the field and reloads the active component.",
        status: "new",
        createdAt: "2026-07-24T18:05:00Z",
        confidenceScore: 0.93,
        rating: 2,
        aiSummary: "Accented characters crash query parameters validator inside search.",
        suggestedAction: "Use encodeURIComponent on text searching inputs and fix character regex.",
        keywords: ["search-glitch", "diacritics", "unicode", "bug"]
    },
    {
        id: "fb-24",
        source: "chat",
        customerName: "Bruce Banner",
        customerEmail: "hulk@avengers.org",
        sentiment: "negative",
        category: "performance",
        content: "Memory leakage detected when leaving the dashboard tab open in Chrome for over 4 hours. Tab size balloons from 120MB to over 1.8GB.",
        status: "in_progress",
        createdAt: "2026-07-24T14:50:00Z",
        confidenceScore: 0.99,
        rating: 1,
        aiSummary: "Dashboard memory leak pushes browser heap over 1.8GB.",
        suggestedAction: "Inspect useEffect hooks in charts for undisposed intervals/subscriptions.",
        keywords: ["memory-leak", "chrome", "charts", "performance"]
    },
    {
        id: "fb-25",
        source: "website",
        customerName: "Diana Prince",
        customerEmail: "diana@themyscira.gov",
        sentiment: "positive",
        category: "feature_request",
        content: "Would love automated categorization for multilingual support tickets. We get reviews in Greek, French, and Spanish, but require categorization in English.",
        status: "new",
        createdAt: "2026-07-23T16:20:00Z",
        confidenceScore: 0.88,
        rating: 4,
        aiSummary: "Multilingual translation parsing requested for inbound feedback.",
        suggestedAction: "Incorporate translation step prior to sending prompt to LLM classification.",
        keywords: ["multilingual", "translation", "features", "translation"]
    },
    {
        id: "fb-26",
        source: "twitter",
        customerName: "Wally West",
        customerEmail: "flash@centralcity.org",
        sentiment: "positive",
        category: "performance",
        content: "Unbelievably quick dashboard reload speed. Clicking between filters is almost instantaneous. Absolute benchmark for React apps.",
        status: "resolved",
        createdAt: "2026-07-23T11:00:00Z",
        confidenceScore: 0.97,
        rating: 5,
        aiSummary: "High satisfaction with SPA dashboard reactivity and rendering speed.",
        suggestedAction: "Congratulate team on keeping state updates optimized.",
        keywords: ["performance", "client-rendering", "latency", "speed"]
    },
    {
        id: "fb-27",
        source: "google",
        customerName: "Arthur Curry",
        customerEmail: "aquaman@atlantis.org",
        sentiment: "neutral",
        category: "pricing",
        content: "Do you have custom volume discounting options for non-profit oceanic conservation societies? Your basic scale doesn't fit high volume/low budget setups.",
        status: "new",
        createdAt: "2026-07-22T13:45:00Z",
        confidenceScore: 0.85,
        rating: 3,
        aiSummary: "Non-profit volume pricing query for oceanic conservation groups.",
        suggestedAction: "Deploy custom discount link to support team for non-profit inquiries.",
        keywords: ["pricing", "discounts", "non-profit"]
    },
    {
        id: "fb-28",
        source: "email",
        customerName: "Barry Allen",
        customerEmail: "barry.allen@ccpd.gov",
        sentiment: "negative",
        category: "bug",
        content: "Excel exported spreadsheets report corrupted characters in name columns containing emojis. My exports are littered with odd characters like â˜.",
        status: "in_progress",
        createdAt: "2026-07-22T08:10:00Z",
        confidenceScore: 0.92,
        rating: 2,
        aiSummary: "Emoji encoding issues lead to garbled strings in xlsx/csv exports.",
        suggestedAction: "Enforce UTF-8 Byte Order Mark (BOM) in CSV generators.",
        keywords: ["csv", "encoding", "emojis", "corruption"]
    },
    {
        id: "fb-29",
        source: "appstore",
        customerName: "Hal Jordan",
        customerEmail: "hjordan@ferrisair.com",
        sentiment: "positive",
        category: "ui_ux",
        content: "The visual summary graphs are straightforward. I can glance once and immediately identify where our main bugs concentrate each week.",
        status: "resolved",
        createdAt: "2026-07-21T17:30:00Z",
        confidenceScore: 0.95,
        rating: 5,
        aiSummary: "Interactive graphs are highly effective for dashboard bug concentration sweeps.",
        suggestedAction: "No action required. Store as UX success log.",
        keywords: ["charts", "visuals", "ux", "summaries"]
    },
    {
        id: "fb-30",
        source: "website",
        customerName: "Selina Kyle",
        customerEmail: "selina@gothamprowl.org",
        sentiment: "neutral",
        category: "other",
        content: "Is there a status page detailing historical downtime? We had some api query failures last Tuesday around 4 AM and want to confirm if it was system maintenance.",
        status: "resolved",
        createdAt: "2026-07-21T09:15:00Z",
        confidenceScore: 0.87,
        rating: 3,
        aiSummary: "Inquiry regarding API availability logs and downtime transparency.",
        suggestedAction: "Share public status page link and configure auto-emails for planned maintenance.",
        keywords: ["status-page", "downtime", "maintenance", "api"]
    },
    {
        id: "fb-31",
        source: "email",
        customerName: "Victor Stone",
        customerEmail: "cyborg@star-labs.com",
        sentiment: "positive",
        category: "performance",
        content: "API schema definition via OpenAPI Spec was generated perfectly. Integrated with our Go codebase in less than half an hour. Kudos on the dev tooling.",
        status: "resolved",
        createdAt: "2026-07-20T16:40:00Z",
        confidenceScore: 0.99,
        rating: 5,
        aiSummary: "OpenAPI generator matches production APIs cleanly, easing integrations.",
        suggestedAction: "Share developers' appreciation with API gateway team.",
        keywords: ["openapi", "dev-experience", "documentation", "go"]
    },
    {
        id: "fb-32",
        source: "survey",
        customerName: "John Constantine",
        customerEmail: "john@constantine-exorcisms.co.uk",
        sentiment: "negative",
        category: "bug",
        content: "The session timeouts are too swift. If I step away for five minutes to fetch coffee I return to find my active drafts destroyed by redirection.",
        status: "new",
        createdAt: "2026-07-20T10:05:00Z",
        confidenceScore: 0.94,
        rating: 2,
        aiSummary: "Auto-logout sweeps drafts because state is not stored in localized cache.",
        suggestedAction: "Persist work-in-progress forms to localStorage before auto-redirecting.",
        keywords: ["session-timeout", "drafts", "local-storage", "bug"]
    },
    {
        id: "fb-33",
        source: "chat",
        customerName: "Stephen Strange",
        customerEmail: "s.strange@kamartaj.edu",
        sentiment: "neutral",
        category: "feature_request",
        content: "It'd be very helpful if we could schedule report exports. Sending a CSV summary to our slack/email distribution list every Monday at 9AM automatically.",
        status: "new",
        createdAt: "2026-07-19T14:45:00Z",
        confidenceScore: 0.90,
        rating: 4,
        aiSummary: "Request for scheduled automated report exports.",
        suggestedAction: "Scope Cron-triggered dashboard reporting pipelines.",
        keywords: ["automation", "reports", "scheduling", "csv"]
    },
    {
        id: "fb-34",
        source: "twitter",
        customerName: "Peter Quill",
        customerEmail: "star-lord@milano.space",
        sentiment: "negative",
        category: "pricing",
        content: "Double-check your taxes calculation. It added VAT twice on our billing checkout, once in the subtotal and once more in the final routing calculation.",
        status: "in_progress",
        createdAt: "2026-07-19T09:12:00Z",
        confidenceScore: 0.97,
        rating: 1,
        aiSummary: "Checkout flow calculates VAT twice during order routing.",
        suggestedAction: "Audit backend billing checkout controller tax additions.",
        keywords: ["tax-calculation", "billing", "checkout", "european-vat"]
    },
    {
        id: "fb-35",
        source: "google",
        customerName: "Carol Danvers",
        customerEmail: "captain@starforce.mil",
        sentiment: "positive",
        category: "performance",
        content: "The analytics engine processes millions of logs in a flash. Render times for historical charts is incredibly rapid. Very impressive tech.",
        status: "resolved",
        createdAt: "2026-07-18T18:30:00Z",
        confidenceScore: 0.98,
        rating: 5,
        aiSummary: "Analytics engine handles large sets with extremely fast rendering.",
        suggestedAction: "No action. Record under performance highlights.",
        keywords: ["analytics", "performance", "rendering", "loading-speed"]
    }
];

// Line Chart: Ingestion and Sentiment Trend
export const mockSentimentChart = [
    { name: "Jan", positive: 400, neutral: 240, negative: 180 },
    { name: "Feb", positive: 500, neutral: 280, negative: 200 },
    { name: "Mar", positive: 650, neutral: 300, negative: 150 },
    { name: "Apr", positive: 800, neutral: 320, negative: 120 },
    { name: "May", positive: 950, neutral: 280, negative: 90 },
    { name: "Jun", positive: 1248, neutral: 340, negative: 130 },
];

// Pie Chart: Issues by Category
export const mockCategoryChart = [
    { name: "Bugs", value: 382 },
    { name: "Features", value: 294 },
    { name: "UI/UX", value: 218 },
    { name: "Performance", value: 184 },
    { name: "Pricing", value: 170 },
];

// Bar Chart: Rating Distribution
export const mockRatingChart = [
    { rating: "5 Stars", count: 450, fill: "#10b981" },
    { rating: "4 Stars", count: 320, fill: "#34d399" },
    { rating: "3 Stars", count: 180, fill: "#fbbf24" },
    { rating: "2 Stars", count: 90, fill: "#f87171" },
    { rating: "1 Star", count: 58, fill: "#ef4444" },
];
